name: integracion continua con node.js

on: [push, pull_request]

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install required dependencies
        run: |
          apt update && apt install --yes sudo
          sudo apt install --yes git
          sudo DEBIAN_FRONTEND=noninteractive apt install --yes npm
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
      - run: npm install -g typescript
      - run: npm i typescript @types/node @types/react @types/react-dom @types/jest
      - run: tsc jobs/pending_payments.ts
      - run: npm ci
      - run: npm test