name: integracion continua con node.js

on: [push, pull_request]

jobs:
  ci_to_main:
    runs-on: ubuntu-20.04
    container:
      image: "ubuntu:20.04"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Update apt and install required packages
        run: |
          apt update
          apt install --yes sudo
          sudo apt install --yes --no-install-recommends curl
      - run: sudo apt-get install --yes gnupg
      - name: Import the public key used by the package management system
        run: |
          sudo rm -f /etc/ssl/certs/ca-bundle.crt
          sudo apt reinstall --yes ca-certificates
          sudo update-ca-certificates
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \
            sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
            --dearmor
      # - run: wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add - 
      - run: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
      - run: sudo apt-get update
      - run: sudo apt-get install --yes mongodb
      - run: mongod --version
      - run: mkdir -p /data/db 
      - run: mkdir -p /data/db/log
      # - run: mongod --dbpath /data/db --fork --logpath /data/db/log
      - name: Start MongoDB
        run: mongod

      - name: Verify that MongoDB has started successfully
        run: sudo service mongod status

      - name: Create database
        run: mongo --eval 'db.getSiblingDB("lnp2pbot").createCollection("mycollection")'

      - run: npm ci
      - name: Run tests
        env:
          DB_USER: ''
          DB_PASS: ''
          DB_HOST: 'localhost'
          DB_PORT: '27017'
          DB_NAME: 'lnp2pbot'
        run: |
          npm test
