name: integracion continua con node.js

on: [push, pull_request]

jobs:
  ci_to_main:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Update apt and install required packages
        run: |
          sudo apt update
          sudo apt install --yes --no-install-recommends curl
          sudo apt-get install --yes gnupg

      - name: Import the public key used by the package management system
        run: |
          sudo rm -f /etc/ssl/certs/ca-bundle.crt
          sudo apt reinstall --yes ca-certificates
          sudo update-ca-certificates
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \
            sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
            --dearmor

      - name: Install MongoDB
        run: |
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          
          # we have to first install the old version of mongodb and after that install the new version. If we don't do this then we won't be 
          # able to run `sudo service mongodb start` because we get `mongod: unrecognized service`. This workaround is copied from the following 
          # issues: https://github.com/microsoft/WSL/issues/796 & https://github.com/microsoft/WSL/issues/796
          sudo apt-get install -y mongodb
          
          # Since we are installing two mongodb version we get the following error:
          # dpkg: error processing archive /tmp/apt-dpkg-install-6TRhGZ/1-mongodb-database-tools_100.7.1_amd64.deb (--unpack):
          # trying to overwrite '/usr/bin/bsondump', which is also in package mongo-tools 3.6.3-0ubuntu1
          # we were able to install the nwe version by overwriting dpkg packages following the instructions in 
          # https://askubuntu.com/questions/176121/dpkg-error-trying-to-overwrite-file-which-is-also-in
          sudo apt-get -o Dpkg::Options::="--force-overwrite" install -y mongodb-org
      - name: Check Mongo version
        run: mongod --version
      - name: Start MongoDB
        run: |
          # we use mongodb service instead of mongod as a result of following the github issues mentioned before
          sudo service mongodb start
      - name: Verify that MongoDB has started successfully
        run: sudo service mongodb status

      - name: Create database
        run: |
          # this sleep is added to avoid race condition without this we sometimes get the following error:
          # connecting to: mongodb://127.0.0.1:27017
          # 2023-05-30T13:02:52.975+0000 W NETWORK  [thread1] Failed to connect to 127.0.0.1:27017, in(checking socket for error after poll), reason: Connection refused
          # 2023-05-30T13:02:52.976+0000 E QUERY    [thread1] Error: couldn't connect to server 127.0.0.1:27017, connection attempt failed :
          # connect@src/mongo/shell/mongo.js:257:13
          # @(connect):1:6
          # exception: connect failed
          sleep 10
          
          mongosh --eval 'db.getSiblingDB("lnp2pbot").createCollection("mycollection")'

      - run: npm ci
      - name: Run tests
        env:
          DB_USER: ''
          DB_PASS: ''
          DB_HOST: 'localhost'
          DB_PORT: '27017'
          DB_NAME: 'lnp2pbot'
        run: npm test
