name: integracion continua con node.js

on: [push, pull_request]

jobs:
  ci_to_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm install @types/node @types/i18n
      - run: tsc jobs/pending_payments.ts
      - run: tsc bot/start.ts
      - run: npm ci
      - run: npm test